services:
  web:
    container_name: advocatus_web
    build: 
      context: ../../web
      dockerfile: ../config/docker/web/Dockerfile
    ports:
      - '3000:5173'
    volumes:
      - '../../web/:/app'