services:
  advocatus_web_app:
    container_name: advocatus_web_app
    build:
      context: ../../advocatus_web_app
      dockerfile: Dockerfile
    ports:
      - '3000:5173'
    volumes:
      - '../../advocatus_web_app/:/app'

  advocatus_personal_manager_ms:
    container_name: advocatus_personal_manager_ms
    build:
      context: ../../advocatus_personal_manager_ms
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
    volumes:
      - '../../advocatus_personal_manager_ms/:/app'
    depends_on:
      - advocatus_personal_manager_db

  advocatus_personal_manager_db:
    container_name: advocatus_personal_manager_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PERSONAL_MANAGER_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PERSONAL_MANAGER_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${PERSONAL_MANAGER_DB}
    ports:
      - '27017:27017'
    volumes:
      - '../../advocatus_personal_manager_ms/database:/data/db'

  advocatus_authentificator_ms:
    container_name: advocatus_authentificator_ms
    build:
      context: ../../advocatus_authentificator_ms
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../advocatus_authentificator_ms/.env 
    volumes:
      - "../../advocatus_authentificator_ms/app:/app/app"
    depends_on:
      - advocatus_authentificator_db
    entrypoint: ["wait-for-it", "advocatus_authentificator_db:3306", "--", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  advocatus_authentificator_db:
    container_name: advocatus_authentificator_db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - '../../advocatus_authentificator_ms/database:/data/db'

  advocatus_cases_ms:
    container_name: advocatus_cases_ms
    build:
      context: ../../advocatus_cases_ms
      dockerfile: Dockerfile
    ports:
      - "8002:8002" 
    env_file:
      - "../../advocatus_cases_ms/.env"
    volumes:
      - "../../advocatus_cases_ms/:/app"
    depends_on:
      - advocatus_cases_db 
  
  advocatus_cases_db:
    container_name: advocatus_cases_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${CASES_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CASES_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${CASES_DB}
    command: --port 27018
    ports:
      - "27018:27018"
    volumes:
      - cases_db_data:/data/db
      - ../../advocatus_cases_ms/mongo_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  advocatus_ag:
    container_name: advocatus_ag
    build:
      context: ../../advocatus_ag
      dockerfile: Dockerfile
    environment:
      AUTH_MS_URL: http://advocatus_authentificator_ms:8000
      PERSONAL_MANAGER_MS_URL: http://advocatus_personal_manager_ms:8001 
    ports:
      - "4000:4000"
    volumes:
      - '../../advocatus_ag/:/app'
    depends_on:
      - advocatus_authentificator_ms
      - advocatus_personal_manager_ms

volumes:
  cases_db_data:
  db_data:
